# Quick boot options
sudo: false
cache:
  directories:
    - node_modules

# Ignore version tags
branches:
  except:
    - /^v[0-9]/

# Language options
language: node_js
node_js:
  - 4

# Coverage report
after_success:
  - export TRAVIS_PASSED=true
  - npm install codeclimate-test-reporter --global
  - codeclimate-test-reporter < coverage/lcov.info
env:
  global:
    # CODECLIMATE_REPO_TOKEN
    - secure: Av1TAFsD8wGlzq9Wq4JzLU9SdnoWgMDUI02rC7IMzTu0oWLbpprSnzUz9Q4gyHreknFAPpjKaq6aK1W/hQL4BwSNkXpZRrim9rKT7RkcXxJxXkmhcT6/gLOLGAn3CPDvEyNBxv9iOKXzt9EemtI0oFsalJh1wPKa82x1QtrkOtys1mvAmnMehh5f2XelwuBLumBAZtBLChI6LfGWhvEVDdTxq4pcEG08ELJ/AAerFlMxQghrbCVmL7N61taM0AzVoHE6QALjg4Q+STQANbwvcQpWQDwP+kuox5TZ7JlkBVaIaFK8pDPxt9E9ezOVpyRBjNODCg6WwXndQc9lZ4qnedJUss1kuODHGeirOG1uGIipO01fqfqKlZF/A698UPWsmqXBRYmeABnT91Lc6zO1JszA21S2OlJMMniFc/M1pmZs77sPKLdQNU+5Ko+7SeSoPGLeoOLyFg41XaAgf1LstrSua5n2UEoaTiCphmqQDV5w6DvOPqUFtVrpMkZA6J5Sly78/WvsPQ1AKI8pn+s1sshclX9A8vGLx9FtZvh9KGxOKDKk6j801bEkmD6332hnPFZBMoHpY8B0/ICwqQVqBxs3gnilV4z+c9u+OYf6MZbgJ2VSAek1Z+ioQPyFSbd9vCp0w+o8M/n4QKa+qGCZYkEkNsNxyPD2s4EFb0YJNb0=

# Npm publish options
deploy:
  skip_cleanup: true# keep the devDependencies
  provider: npm
  email: i59naga@icloud.com
  api_key:
    secure: m0bUQ1QSgeK8/JrPcLI2AL5XR4T6SFTgfKIRrym/WvzJiZsOHtxixmcr4fn6ToNCscFLT3iVJFbPySC2Bib4jLQ2sKuruE7Gf8F9801joEMK1h8oaYX4WxLeThMP9eLgki+g2xWlKIqJc1YhZemr5a2GOaYTsvV9ioISiApuQp7cwe6PcpprKQ2gxkMIYI+wAtWzwmS1H3Q1pMZLSmX2IBHTNCLPVJdZBl6nHvFjRO+e5ks6UIX3AXRmnX2AEDB17cZLnm9wbMsqUq7Kjs37zaB6qXeHvgRuIlm7UKWilFAnKxUu2faQb4LRbX0W+pmRc5g2lEoO/MBuICA+5P4NjgehHA7HptyhtmHWigIFqY+ixjB/0k8nG1CpJq2GMzxt8h71Tcq7NjjeOFU4JtOc6bZefBkZ2yP0m4FbuJEBWcJUkep/5SfW2XMIk3GvY0StLTrY4JOLlO4k2k/DPpRzW+9lwHn+WlHyXPbmsX8pCO2qVC6c/hldeZIiy4o+VtnlHwC7nzScY86SWeNxbGs7Ut/cfCh0aJ/xFANmhkMXrntuu9QDNFBS/v+kwbDD07suoNU2futS3w/XUqXA1GfYZ+ym5YVSmc31uYZQqDFXdG7R3Pnh6V9lGKOye4bkXUV3eVxzF6Fa2O2d/NKnoaEohrch78RAxs2VUujzpTHRcJA=
  on:
    node: 4